stages:
  train_model:
    cmd: python train.py
    deps:
    - data/sign_mnist_test_v1.csv
    - data/sign_mnist_train_v1.csv
    - train.py
    outs:
    - trained_models/sign_cnn_best.pth
    metrics:
    - metrics.json:
        cache: false
