name: CI/CD Docker Build and Push

on:
  push:
    branches:
      - deploy
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/sign-lang-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sign-lang-app:latest
